// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCQNRquRgg2YWLbSvA6QG2n8dvcBDg6_c',
    appId: '1:402669899669:web:0fc9d57090e451b0c0309c',
    messagingSenderId: '402669899669',
    projectId: 'finance-bunny-83a83',
    authDomain: 'finance-bunny-83a83.firebaseapp.com',
    storageBucket: 'finance-bunny-83a83.appspot.com',
    measurementId: 'G-KPGJ7ZZB34',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPy16hEK-yTAkkK8STAi_LyX2HeY_iikA',
    appId: '1:402669899669:android:25f5f3640437e709c0309c',
    messagingSenderId: '402669899669',
    projectId: 'finance-bunny-83a83',
    storageBucket: 'finance-bunny-83a83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARkVm5pX5AoUGAK_Pt3xhkcwtTDP21IH4',
    appId: '1:402669899669:ios:31e8f2388aec2ec9c0309c',
    messagingSenderId: '402669899669',
    projectId: 'finance-bunny-83a83',
    storageBucket: 'finance-bunny-83a83.appspot.com',
    iosBundleId: 'com.example.financeBunny',
  );
}
